version: '3.2'

services: 
  simple-app:
    image: simple-app
    build:
        context: .
        dockerfile: development.dockerfile
    volumes:
        - "../.:/go/src/github.com/reyhanfahlevi/simple-app"
    ports:
        - "4040:4040"
    depends_on:
        - mysql
    command: ["refresh","run","-c",".dev/refresh.yaml"]
    container_name: simple-app
    networks:
      sampleapp:
  mysql:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER : devel
      MYSQL_PASSWORD : devel
    volumes:
      - ../.dev/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql
    networks:
      sampleapp:

networks:
  sampleapp: